<div id="toppage"> 
			<img src="./logo.jpg">
			<label id="title"> QUẢN LÍ THƯ VIỆN </label>
			<div id="identiy"> 
				<nav>
			<ul style="list-style: none">
				<li>
					<a href="#"> Xin chào, <?php echo $name ?> </a>
						<ul style="list-style: none">
							<li>
								<a href="./login.php" style="display: block"> Logout </a>
							</li>
						</ul>
					</li>
				</ul>
				</nav>
			 </div>
		</div>
<div id="sidepage">
			<div id="sp_1">
				<p> Xin chao, <a href="./staff.php"><?php echo $name ?></a></p>
				<img src="smile.jpg">
			</div>
			<div id="sp_2">
				<p> QUẢN LÝ THƯ VIỆN <p>
					<ul style="line-height: 50px;color: #A4A6F6">
						<li>
							<a href="./home.php"> Trang chủ</a>
						</li>
						<li>
							<a href="./student.php"> Sinh Viên</a>
						</li>
						<li>
							<a href="./book.php"> Sách </a>
						</li>
					</ul>
			</div>
			<div id="sp_3">
				<p> QUẢN LÝ MƯỢN/TRẢ SÁCH <p>
					<ul style="line-height: 50px; color: #A4A6F6">
						<li>
							<a href="borrow_sv.php"> Mượn sách</a>
						</li>
						<li>
							<a href="return.php"> Trả sách </a>
						</li>
						<li>
							<a href="thongke.php"> Thống kê </a>
						</li>
					</ul>
			</div>
			<div id="sp_4">			
		</div>
</div>